"""add patient severity fields

Revision ID: e2f6b062b1cc
Revises: 
Create Date: 2025-12-26 21:27:52.022670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2f6b062b1cc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('severity_score', sa.Float(), nullable=True))
    op.add_column('patients', sa.Column('priority_level', sa.String(), nullable=True))
    op.add_column('patients', sa.Column('last_scored_at', sa.DateTime(), nullable=True))
    op.add_column('patients', sa.Column('external_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_patients_external_id'), 'patients', ['external_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patients_external_id'), table_name='patients')
    op.drop_column('patients', 'external_id')
    op.drop_column('patients', 'last_scored_at')
    op.drop_column('patients', 'priority_level')
    op.drop_column('patients', 'severity_score')
    # ### end Alembic commands ###
